### ISSUE TITLE
Provide missing site ids

### ISSUE THREAD

**Issue by mlonneman** [Smithsonian/CCN-Data-Library#39]
Many depthseries intervals are missing site ID values that exist on core-level metadata. It is being added in the CCRCN map application, which is not an ideal location to do this. Ensure all depthseries entries have site IDs within the hook scripts in the data library.

**Comment by jaxinewolfe** [comment]
The following studies have core tables with missing site_ids: 
"Thom_1992" 
"Copertino_unpublished"

The following studies have depthseries tables with missing site_id:
   study_id                  site_id
 1 Watson_and_Byrne_2013     NA     
 2 Thom_1992                            NA 
 3 Breithaupt_et_al_2017     NA     
 4 Cochran_et_al_1998        NA     
 5 Noe_et_al_2013            NA     
 6 CRMS_Database             NA     
 7 Drake_et_al_2015          NA     
 8 Elsey_Quirk_et_al_2011    NA     
 9 Hill_and_Anisfeld_2015    NA     
10 Kulawardhana_et_al_2015   NA     
11 Merrill_1999              NA     
12 Neubauer_2002             NA     
13 Nuttle_1996               NA     
14 Nyman_et_al_1993          NA     
15 Orson_1990                NA     
16 Pastore_et_al_2017        NA     
17 Piazza_et_al_2011         NA     
18 Radabaugh_et_al_2018      NA     
19 Windham_Meyers_et_al_2010 NA     
20 Drexler_et_al_2009        NA

@cheneyr @BettsH Most of these are in the Holmquist 2018 synthesis. Except Watson and Byrne 2013, Thom 1992, and Drexler 2009 I believe. The core tables in each of these hook scripts should have all the site IDs. I would just create a lookup table of study and sites from those IDs and join it to the depthseries. I'll take on Thom 1992 since to see what's going on there in both of the tables. Don't worry about Copertino. Leave a comment to indicate which studies you're taking on so we don't edit the same hook scripts and have a merge conflict :)

**Comment by cheneyr** [comment]
@jaxinewolfe @BettsH I can start looking at Watson and Byrne 2013!

**Comment by jaxinewolfe** [comment]
Great! I'll take the Holmquist 2018 as well and @BettsH you take the Drexler 2009?

**Comment by BettsH** [comment]
added missing site_id to Drexler et al 2009

**Comment by BettsH** [comment]
Here's a checklist of the studies to mark off which are done:

- [ ] Thom_1992: Jaxine
- [ ] Copertino_unpublished
- [ ] Watson_and_Byrne_2013: Rose
- [ ] Breithaupt_et_al_2017 
- [ ] Cochran_et_al_1998 
- [ ] Noe_et_al_2013 
- [ ] CRMS_Database 
- [ ] Drake_et_al_2015
- [ ] Elsey_Quirk_et_al_2011
- [ ] Hill_and_Anisfeld_2015
- [ ] Kulawardhana_et_al_2015
- [ ] Merrill_1999 
- [ ] Neubauer_2002 
- [ ] Nuttle_1996 
- [ ] Nyman_et_al_1993 
- [ ] Orson_1990 
- [ ] Pastore_et_al_2017 
- [ ] Piazza_et_al_2011 
- [ ] Radabaugh_et_al_2018 
- [ ] Windham_Meyers_et_al_2010 
- [ ] Drexler_et_al_2009: Henry
