### ISSUE TITLE
Howard and Fourqurean 2020 data hook 

### ISSUE THREAD

**Issue by cheneyr** [Smithsonian/CCN-Data-Library#70]
- [x] complete data curation
- [x] QAQC
- [ ] managers review

**Comment by jaxinewolfe** [comment]
Hi @cheneyr nice job on this curation! I have a couple of notes you can address when you can:

- sorry if this is a pain, but I think we should recode the last four site IDs (bob, rb, nm, tc) to be more unique/descriptive. You can match them to this table in [Online Resource 4](https://aslopubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Flno.10621&file=lno10621-sup-0001-suppinfo.pdf). I think there are only two places you'd need to do this recode (sites and full_data)
- methods: there is a Fourqurean regression to model %C, but since they measured it (and we verified this by plotting it), fraction_carbon_method = "EA" (here is the [paper they referenced](http://serc.fiu.edu/seagrass/pubs/2012_FourqureanEtAl2.pdf)). Perhaps in the carbon profile notes, you can indicate that "organic C was calculated as the difference between inorganic C and total C".
- depthseries: for better/worse, we don't describe depths as negative, so multiple the depths by -1 (or take the absolute value) to make them positive values. We may want to ask Jim what the best way to represent these depth intervals is since we usually work with concrete intervals and the representative depths are more for sampling across soil horizons. They cited the methods used in [this paper](https://link.springer.com/article/10.1007/s12237-014-9802-9#Sec2), but it all seems very approximate.
- columns are reordered later on in the synthesis, but if you'd like to reorganize each table, theres a reorderColumns(table_type, df) curation function you can use instead of having to use relocate() multiple times!
- Another useful curation function I added is notAllNA() which you can use to eliminate columns that are all NA. Example: .... %>% select(where(notAllNA))

**Comment by jaxinewolfe** [comment]
@cheneyr Just scanning data hooks in prep for synthesis. Unfortunately, I don't think we should include this one until we have confirmation on the depth intervals (esp. since there's a depth weighted averaging feature in the updated Atlas) along with the coordinate position method. Small fix: distinct() the core table so it collapses into unique cores. Everything else looks great!
