### ISSUE TITLE
Rodriguez et al 2022 data hook

### ISSUE THREAD

**Issue by BettsH** [Smithsonian/CCN-Data-Library#71]
- [x] complete data curation
- [ ] QAQC
- [ ] manager review

**Comment by jaxinewolfe** [comment]
@BettsH Looks great! Here's a few notes:

- cores: position_method = "RTK", and since they provide the vertical and horizontal accuracy in the paper you can include that too: "average vertical error ±2–3 cm (elevation_accuracy) and horizontal error (position_accuaracy) of <1 cm"
- include the methods table in the table_names for QAQC. Side note: I saw that you wrote out every column that wasn't populated with information. To save you (and all of us) time in the future, I have added a curation function called notAllNA(), which you can use like this: methods <- methods_raw %>% select(where(notAllNA))
- species table: looks like code_type "genus" should be "Genus", which is knit picky but our QA tests are case sensitive. Also, could you add "sp." to the species since they aren't identified to the species level (ex. Juncus sp.). 
- in the methods and depthseries tables, you can add method_id = "single set of methods"
- for the c14_material in the depthseries table, you can say "plant fragment" for c14_age that are not NA. Also, there are NA's in the c14 columns "n/a" which you can recode as NA. Two ways you could do this: use the function na_if() within mutate(), or specify the "na ="  argument in read_csv().
- not super important since the columns get reorganized later in the synthesis, but if you want to reorder the columns of each table according to the CCN guidance there's a curation function called reorderColumns(table_type, df) you could use

**Comment by jaxinewolfe** [comment]
@BettsH I just noticed that the study ID in the derivative tables Curtis et al 2022, but I can't figure out how because the hook script assigns Rodriguez to study_id. Are you seeing the same thing?
