### ISSUE TITLE
Data hook: Snedden 2018

### ISSUE THREAD

**Issue by cheneyr** [Smithsonian/CCN-Data-Library#75]
- [x] curation
- [x] QAQC
- [ ] manager review

**Comment by cheneyr** [comment]
Hi @jaxinewolfe! Just wanted to mention you here- if you have notes or edits let me know!

**Comment by jaxinewolfe** [comment]
Thanks @cheneyr Looks great! 

Unfortunately, I think we should drop elevation since its site-level. carbonates removed can be "FALSE" since they measured total carbon, and there's no documentation of processing the sediment for carbonate removal. For position_method, I would guess that its high resolution, but the actual method would need to be confirmed with Greg. In the past for CRMS network cores, we've included a position_note: "coordinates were likely high quality but may refer to a general area rather than individual core location". So let's include this as a note for now. 

Fraction carbon is definitely measured based on the LOI relationship, but the metadata doesn't specify the use of an Elemental Analyzer so we can keep it as "not specified" for now. Could be worth reaching out to Greg to fill in both of these blanks.

@HolmquistJ I feel this is a common case where coordinates are survey grade but site-level so it ends up being low resolution in relation to the actual coring location. Earmarking this for the database vocabulary discussion in the new year.

**Comment by cheneyr** [comment]
@jaxinewolfe Thanks! I'll reach out to Greg to clarify the position method and fraction carbon method.
